### ISSUE TITLE
cron/block.js getinfo 401

### ISSUE THREAD

**Issue by ProjectHelixCoin** [bulwark-crypto/bulwark-explorer#76]
## Expected Behavior
Run block.cron

## Actual Behavior
```
getinfo 401
Error: 401
    at rpc.call (/home/crazy/Bulwark-explorer/lib/rpc.js:51:18)
    at IncomingMessage.<anonymous> (/home/crazy/Bulwark-explorer/node_modules/node-bitcoin-rpc/lib/index.js:70:7)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
{ Error: ENOENT: no such file or directory, unlink '/home/crazy/Bulwark-explorer/tmp/block.cron_lock'
    at Object.unlinkSync (fs.js:952:3)
    at Object.unlock (/home/crazy/Bulwark-explorer/lib/locker.js:40:6)
    at update (/home/crazy/Bulwark-explorer/cron/block.js:157:14)
  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: '/home/crazy/Bulwark-explorer/tmp/block.cron_lock' }
```

## Steps to Reproduce the Problem

  1. Follow the exact steps of: https://github.com/bulwark-crypto/bulwark-explorer
  2. run ./script/cron_block.sh

## Specifications

  - Version: Master branch newest
  - Platform: Linux
  - Subsystem: Ubuntu

**Comment by ProjectHelixCoin** [comment]
Made a type
